### ISSUE TITLE
Format of solution

### ISSUE THREAD

**Issue by luohwu** [cmm-21/a4#10]
Hi Yue,

Can I write a readme.pdf with all my solutions in it? Because it is not easy to write some formulations in readme.md. And it's also not easy to read formulations in readme.md.

So would it be ok taht I write a readme.pdf,  and say "please check readme.pdf for all solutions" in readme.md?

**Comment by liyuesolo** [comment]
yes

**Comment by luohwu** [comment]
Cool. Thank you and good night

**Comment by Glanfaloth** [comment]
I had the same question about rendering formulae in README.md and I found this: https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b

Maybe it would be helpful to you @luohwu ^^

**Comment by luohwu** [comment]
@Glanfaloth  Thank you. That helps a lot. : )
