### ISSUE TITLE
Can we change minimizer for challenge problem

### ISSUE THREAD

**Issue by nicolas-git** [cmm-21/a4#12]
Hey,
Are we allowed to change the gradient descent solver in manip-app.cpp for the regularization task to e.g. NewtonFunctionMinimizer?

**Comment by liyuesolo** [comment]
Of course! I'm excited to see your implementation of the Hessian of the objective function!

**Comment by nicolas-git** [comment]
Hmm, isn't the hessian for the newton solver already implemented via finite differences?

**Comment by liyuesolo** [comment]
right, you can do finite difference, in practice I wouldn't do it for several reasons but, sure, why not explore it! Let me know how it goes in your Readme.

**Comment by nicolas-git** [comment]
oh yeah I see the problem now when dynamics come into play. is there a way to speed up convergence of gradient descent with line search? since convergence is the main problem i did not want to use it. if you can answer this without revealing too much :) thx!

**Comment by liyuesolo** [comment]
how about quasi-Newton methods like lbfgs. you can use an external library if you want.

**Comment by liyuesolo** [comment]
or change the objective/regularizor you defined

**Comment by luohwu** [comment]
@liyuesolo  Wait. Are we required to implement the dynamics?

**Comment by liyuesolo** [comment]
@luohwu no

**Comment by nicolas-git** [comment]
oh. so, if the behavior when dynamics are activated does not matter, but works more or less fine otherwise, will we get full points? of course the findings are reported in the readme.

**Comment by liyuesolo** [comment]
@nicolas-git Yes.

**Comment by luohwu** [comment]
Thank you
