### ISSUE TITLE
"cocoa_platform.h" headers missing

### ISSUE THREAD

**Issue by swellsc** [cmm-21/a4#13]
Hi, after my Xcode command line tools automatically updated a few days ago, a bunch of my header files were no longer located by my c++ compiler. After going through all related issues I could find on the internet, I was able to solve the relocated path for c header files, etc., but was left with some remaining missing headers. Specifically, I now get the issue:

[  5%] Built target nanovg
[ 10%] Built target glad
[ 12%] Building C object ext/glfw/src/CMakeFiles/glfw.dir/context.c.o
In file included from /Users/sandra/Desktop/CMM/a4-swellsc/ext/glfw/src/context.c:30:
In file included from /Users/sandra/Desktop/CMM/a4-swellsc/ext/glfw/src/internal.h:183:
/Users/sandra/Desktop/CMM/a4-swellsc/ext/glfw/src/cocoa_platform.h:28:10: fatal error: 'dlfcn.h' file not found
#include <dlfcn.h>
1 error generated.
make[2]: *** [ext/glfw/src/CMakeFiles/glfw.dir/context.c.o] Error 1
make[1]: *** [ext/glfw/src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

I handed in my assignment as it is because I had almost finished the coding part before this happened, anyway. But since I am not finding any solution online I am wondering whether you have some insight on why this code might be failing on my computer. Especially, since other projects that I am building are not running into this issue.

Thanks a lot in advance!

**Comment by liyuesolo** [comment]
@eastskykang @moritzge

**Comment by liyuesolo** [comment]
Have you tried deleting your CMake cache, configure and make again. Like everything from scratch.

**Comment by swellsc** [comment]
Wow, that fixed it. Thank you! I wish I had asked earlier! :)

**Comment by liyuesolo** [comment]
well, you still have half an hour to make a final push.

**Comment by swellsc** [comment]
I managed to solve my final code issues in the last half an hour :) 
However, I took an extra 5 minutes to remove the description of the issue in the readme, accordingly. I hope it can be considered anyway. Otherwise, the answers to all the questions are the same before 6pm, and just know that I no longer had the issue in the final commit. Thanks again!

**Comment by liyuesolo** [comment]
very good!
