### ISSUE TITLE
can we use the implemented hessian/ mani-app.cpp

### ISSUE THREAD

**Issue by vullnetu** [cmm-21/a4#2]
I wanted to ask whether we can use get_H(u,x) to calculate dFdx in if(step== ANALYTIC_dFdu) or do we need to implement it our own ?
Can you also elaborate this equation a little bit more: --> p' = o + R_theta{f} + xy;

**Comment by liyuesolo** [comment]
Hi,
Yes, you can, as the HINT suggested in the write-up? Did you see the comment above? pin.anchorPosition = o + rotate_(from_(o, s_X), theta) + T; you can further go to femLib/Simulation.h to check out updatePinAnchorsAccordingToHandles() function implementation. Could you elaborate more regarding your confusion? You can print out the values to figure out what they are.

**Comment by vullnetu** [comment]
Okay thanks, yes I was not sure if this hint belongs to the previous task.

Yes the definitions of the variables were confusing me. It's clear now thanks.

**Comment by liyuesolo** [comment]
o is the predefined handle center, basically, around which point we rotate the end of the bar, T is the translation of the handle center and theta is the rotation angle. the pins are basically parameterized by these parameters. Feel free to bring up any questions in the tutorial again.
