### ISSUE TITLE
Question 9

### ISSUE THREAD

**Issue by iqiac** [cmm-21/a4#3]
In Q9, it says "we can compute (partial F/partial x) analytically", but you actually mean (partial F/partial u), right? So the goal is to complete `get_dFdu()`

**Comment by liyuesolo** [comment]
we can compute (partial F/partial x) analytically belongs to Q8, for Q9 yes you need to compute dFdu

**Comment by liyuesolo** [comment]
sorry, yes you are right, should be dFdu.

**Comment by iqiac** [comment]
Ok, thanks for clarifying.
