### ISSUE TITLE
Simulation super slow

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a4#4]
Dear TAs

I ran the app on my computer and I noticed that, even before I coded anything, it runs very slowly. The simulation lags a lot. I wnted to ask: Is this because some stuff is missing in the code (meaning if I finish the exercise, it will run faster) or will it only get worse? Maybe I have to see if I get access to a faster computer then....

Have a nice weekend! and thank you in advance!
Manuel

**Comment by liyuesolo** [comment]
are you sure you are running in Release mode, not in debug?

**Comment by Maenzgi** [comment]
That could be it, thank you!
