### ISSUE TITLE
Check matrix of task 9

### ISSUE THREAD

**Issue by madBot42** [cmm-21/a4#5]
Hi

according to the function checkMatrixXd in the function F_wrapper (to check the matrix from task 9) I would expect that it would print out [MATCH] if the matrix is implemented in the right way (and it printed [MISMATCH] when it wasn't). 

But as it doesn't (see picture), does it mean I still have a wrong implementation?

![image](https://user-images.githubusercontent.com/26327636/116009488-4f04b080-a61a-11eb-9b72-7b1fb3d0c122.png)

**Comment by Rasilu** [comment]
I assume you have implemented it correctly. For me it only shows something if I have MISMATCH. Try implementing it wrong intentionally and see if you get MISMATCH. 
Or maybe you have not tried moving around the target points?

**Comment by liyuesolo** [comment]
Hi 

Apologies for setting the default printing argument to be false, yes printing nothing can be confusing, please use checkMatrixXd(matFD(u, F_wrapper), dFdu, false, true); and check again. and @Rasilu is correct, it will only print if your implementation is wrong.

**Comment by madBot42** [comment]
Thanks to you both!

@Rasilu First I had [MISMATCH] when it was wrong and I was dragging the points around. After updating and looking at the checkMatrix-function I expected to have [MATCH] if it were right so I suspected that it's "not that wrong" but also "not right". nice gang btw :)

@liyuesolo No worries! I changed it and now it prints [MATCH]. 👍
