### ISSUE TITLE
Question 6

### ISSUE THREAD

**Issue by TunVunDerBunn** [cmm-21/a4#6]
Dear TA's,

I do not understand exactly what you mean by FD_BIG_PIECES in question 6. I am already thinking a couple of days about it and I do not come forward. I assume that we can not use the get_H function or the solve_Ax_EQUALS_B function already in this question. Is this right? I see that dO/dx and dx/du can be computed using newtons method, but should we then approximate all the terms needed to apply newtons method with a finite difference method (like the hessian and so on)?

Thank you very much already in advance.

**Comment by liyuesolo** [comment]
Hi, 

For FD_BIG_PIECES, you only need to compute the total gradient dO/du using the finite-difference results of dOdx and dxdu.

**Comment by TunVunDerBunn** [comment]
Okay I understand, thank you very much.
