### ISSUE TITLE
manip-app only runs if "OPTIMIZE" checked

### ISSUE THREAD

**Issue by swellsc** [cmm-21/a4#7]
Hi, when running manip-app, the bar only moves if I check the box "OPTIMIZE". Is this expected? Or does it indicate a problem with my code? Thanks a lot!

**Comment by nwicki** [comment]
This is as expected. When checking the optimize box we try to solve the given problem (moving the positions of feature points as close to the requested position as possible) by minimizing the squared distance and therefore optimizing the solution to the given problem.

**Comment by swellsc** [comment]
Ah perfect, I thought it was some simulation optimization. Thank you!
