### ISSUE TITLE
Challenge Problem: Question 12

### ISSUE THREAD

**Issue by nwicki** [cmm-21/a4#8]
When we are to implement the regularizer in question 12 there already exists a conditional statement to include it in the function evaluate() Line 28, but it is never used during the derivation. Shouldn't it be placed into the function get_O() Line 40?

**Comment by liyuesolo** [comment]
Hi,

You can easily see if that function is been called by printing something inside the function. Finding out how it is used should be part of your assignment.

**Comment by nwicki** [comment]
Ok
